### ISSUE TITLE
请问怎么得到图片像素点对应的相位

### ISSUE THREAD

**Issue by WUHUHAHA** [XuRuLin/FSMH_Library#1]
是用gs算法吗

**Comment by XuRulin** [comment]
可以使用GS算法生成，也可以是其他的算法。这个仓库里的代码不涉及全息算法，只负责根据相位数据文件绘制FDTD的仿真模型。如何生成相位数据文件可以参考[HoloLib_MATLAB](https://github.com/HoloLib/HoloLib_MATLAB)里的writeFDTD函数。

**Comment by WUHUHAHA** [comment]
感谢您的回复，我再研究一下您说的代码。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HoloLib/FDTD-Solutions-Script-Library"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月12日(星期六) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HoloLib/FDTD-Solutions-Script-Library] 请问怎么得到图片像素点对应的相位 (Issue #1)





 
可以使用GS算法生成，也可以是其他的算法。这个仓库里的代码不涉及全息算法，只负责根据相位数据文件绘制FDTD的仿真模型。如何生成相位数据文件可以参考HoloLib_MATLAB里的writeFDTD函数。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
